runtime: nodejs10
service: default

instance_class: F2

handlers:
  - url: /_nuxt
    expiration: '365d'
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    expiration: '365d'
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    redirect_http_response_code: 301
    secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  BACKEND_URL: '/api/graphql'
